### ISSUE TITLE
💡 Proposal - Refactor to function components 

### ISSUE THREAD

**Issue by denkristoffer** [contentful/forma-36#651]
# Forma 36 contribution proposal

## The problem

Forma 36 currently uses a mix of class and function components. There are no difference between the two for consumers of the package, but function components are preferable for us Forma 36 developers for a few reasons:

- Hopefully building all components in the same way makes it easier to understand the codebase and easier to contribute to F36. I think this is especially true for newcomers to React, who might not even have learned how to build class components.
- They allow for the use of hooks.
- They allow us to migrate away from defaultProps to normal JS default values.

## The proposed solution

- [x] ~~Accordion: Is already a function component~~
- [x] ~~Asset: Under way in #652~~
- [x] ~~Autocomplete: Is already a function component~~
- [x] ~~Button: Under way in #641~~
- [x] ~~Card: Under way in #648~~
- [x] ~~Checkbox: Under way in #641~~
- [x] ~~CheckboxField: Under way in #641~~
- [x] ~~ControlledInput: Under way in #641~~
- [x] ~~ControlledInputField: Under way in #641~~
- [x] ~~CopyButton: Under way in #652~~
- [x] ~~DateTime: Is already a function component~~
- [x] ~~RelativeDate: Is already a function component~~
- [x] ~~Dropdown: Is already a function component~~
- [x] ~~EditorToolbar: Under way in #652~~
- [x] ~~EmptyState: Under way in #717~~
- [x] ~~EntityList: Is already a function component~~
- [x] ~~FieldGroup: Under way in #641~~
- [x] ~~Flex: Is already a function component~~
- [x] ~~Form: Under way in #641~~
- [x] ~~FormLabel: Under way in #641~~
- [x] ~~Grid: Is already a function component~~
- [x] ~~HelpText: Under way in #717~~
- [x] ~~Icon: Under way in #717~~
- [x] ~~IconButton: Under way in #641~~
- [x] ~~Illustration: Under way in #717~~
- [ ] InViewport: This is going to be bothersome to changerefactor
- [x] ~~List: Under way in #717~~
- [x] ~~Modal: Under way in #717~~ 
- [x] ~~Note: Under way in #717~~ 
- [x] Notification components: Under way in #720
- [x] ~~Option: Under way in #641~~
- [x] ~~Pill: Is already a function component.~~
- [x] ~~Portal: Is already a function component.~~
- [x] ~~ProductIcon: Is already a function component.~~
- [x] ~~RadioButton: Under way in #641~~
- [x] ~~RadioButtonField: Under way in #641~~
- [x] ~~Select: Under way in #641~~
- [x] ~~SelectField: Under way in #641~~
- [x] ~~Skeleton components: Under way in #717~~
- [x] ~~Spinner: Under way in #654~~
- [x] ~~Switch: Is already a function component.~~
- [x] ~~TabFocusTrap: Under way in #717~~
- [x] ~~Table components: Underway in #660~~
- [x] ~~Tabs: Under way in #717~~
- [x] ~~Tag: Under way in #717~~
- [x] ~~Textarea: Under way in #641~~
- [x] ~~TextField: Under way in #641~~
- [x] ~~TextInput: Under way in #641~~
- [x] ~~TextLink: Under way in #717~~
- [x] ~~ToggleButton: Under way in #641~~
- [x] ~~Tooltip: Is already a function component.~~
- [x] ~~Typography components: Under way in #717~~
- [x] ~~ValidationMessage: Under way in #717~~
- [x] ~~Workbench: Is already a function component.~~

## Breaking changes

Hopefully none, otherwise we can push these changes to v4.

**Comment by m10l** [comment]
This would be great. I think we should add updating the plop templates in this list too as they're intended to give all components the same start

**Comment by mshaaban0** [comment]
Awesome, this should help a lot with #304 
The following components has been already covered in the form-controls refactor PR #641 

- [X] Button
- [x] Checkbox
- [x] CheckboxField
- [x] ControlledInput 
- [x] ControlledInputField
- [x] FieldGroup
- [x] Form
- [x] FormLabel
- [x] IconButton
- [x] RadioButton
- [x] RadioButtonField
- [x] Option
- [x] Select
- [x] SelectField
- [x] TextField
- [x] TextInput
- [x] Textarea
- [x] ToggleButton

**Comment by gui-santos** [comment]
Amazing! Let's do it

I was working on the Spinner last Friday and made it FC too
I will open the PR today 🙌
